"""pydantic model for one row of `meta/tasks.jsonl`.

Per-task vocabulary derived from `workflow_description.json`. Each
row is a strict projection of one entry in
`workflow_description.json:_task_routing` — same `task` keys, with
`phase_id` resolved and the phase's `step` and `gesture` blocks
inlined so consumers can read the JSONL alone without joining back
to the workflow JSON.

`meta/tasks.jsonl` is now auto-generated by the build (see
`encode/tasks_jsonl.py`). The earlier hand-authored
`config/surgsync/tasks.jsonl` has been retired — `verbalize_*` and
the parquet cells already source from the workflow JSON, and a
hand-authored tasks.jsonl was an avoidable drift surface.
"""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class TaskVocab(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Identity.
    task: str                       # key in workflow_description.json:_task_routing
    phase_id: str                   # value in _task_routing, e.g. "1" for suturing

    # Phase-level prose (workflow_description.json:phases.<phase_id>.description).
    phase_description: str

    # Per-phase vocabs — verbatim copies of the phase's `step` and
    # `gesture` dicts from workflow_description.json. Keys are JSON
    # strings (matching how the raw annotation GUIs write ids).
    # Empty dict ⇒ the phase has no vocab for that level
    # (e.g. peg_transfer has no gesture vocab).
    step_vocab:    dict[str, str] = Field(default_factory=dict)
    gesture_vocab: dict[str, str] = Field(default_factory=dict)
