stage: kinematic_map
folder_initialize: false

# custom configurations
img_size: [1920, 1080]
arm_name: ['PSM1']
input_subfolder: 'replay'
output_subfolder: "${.stage}"
fps: 30
sigma_x: 10
sigma_y: 10
camera_calibration_path: "${workspace}/data/camera_calibration" # use your own path
weight_adv: true
