stage: kinematic_map
folder_initialize: false

# custom configurations
img_size: [640, 480]
arm_name: ['PSM1', 'PSM2']

input_folder: '${path_config.intermediate_dir}/regular'
output_folder: "${path_config.processed_dir}/${.stage}"

weight_config:
  sigma_x: 50
  sigma_y: 50
  advanced_weight: true
  tol_dist: 0.05

fps_img: 30
fps_kin: 1000
enable_overlay: true
