data_dir: "C:/Users/lc/Desktop/JHU_Course/CIS2/SurgPoseV1/data"
data_name: "data_20250719"
data_index: "3"
raw_dir: "${.data_dir}/${.data_name}/${.data_index}"
intermediate_dir: "${.data_dir}/interm/${.data_name}/${.data_index}"
processed_dir:  "${.data_dir}/output/${.data_name}/${.data_index}"