data_dir: "/home/jackzhy/dvrk_multimodal_data_collection/data"
#data_name: "data_20250808"
#data_index: "3"
data_name: "data_20250903_ubc/suturing"
data_index: "1"
#data_name: "data_ubc_20250814"
#data_index: "ubc03"
raw_dir: "${.data_dir}/${.data_name}/${.data_index}"
intermediate_dir: "${.data_dir}/interm/${.data_name}/${.data_index}"
processed_dir:  "${.data_dir}/output/${.data_name}/${.data_index}"