data_dir: "/media/jackzhy/Jack_SSD/2026_ICRA_materials/data"
data_name: "data_20250809"
data_index: "1"
#data_name: "data_20250904/dissection2"
#data_index: "5"
#data_name: "data_20250911/interpolation"
#data_index: "3"
#data_name: "data_ubc_20250814"
#data_index: "ubc03"
raw_dir: "${.data_dir}/${.data_name}/${.data_index}"
intermediate_dir: "${.data_dir}/interm/${.data_name}/${.data_index}"
processed_dir:  "${.data_dir}/output/${.data_name}/${.data_index}"