data_dir: "/home/jackzhy/SurgPoseV1/data"
data_name: "data_20250712"
data_index: "2"
raw_dir: "${.data_dir}/${.data_name}/${.data_index}"
intermediate_dir: "${.data_dir}/interm/${.data_name}/${.data_index}"     # use if required
processed_dir:  "${.data_dir}/output/${.data_name}/${.data_index}"