defaults:
  - path_config: jack_local     # pick one file from the data, data load and store paths
  - preprocess: rectify_resize  # select the preprocess type
  - _self_

workspace: "/home/jackzhy/dvrk_multimodal_data_collection"

camera_calibration_path: "${workspace}/data/camera_calibration" # use your own path

camera_names: ['left', 'right']
camera_offset:
#camera_offset: [-1.0, 0.0, 0.0,
#                0.0, -1.0, 0.0,
#                0.0, 0.0, 1.0]
# ### Add random seeds if required
# seed: 42

# ### Optional, define log output if required
#hydra:
#  run:
#    dir: "/home/jackzhy/dvrk_multimodal_data_collection/outputs/logs/${now:%Y%m%d}_${now:%H%M%S}"

# custom configurations
