defaults:
  - path_config: jack_local     # pick one file from the data, data load and store paths
  - _self_

#workspace: "/media/jackzhy/Jack_SSD/multi_modal_data/JHU"

workspace: "/media/jackzhy/Jack_SSD/multi_modal_data/UBC"

suture_name: "data_20250903_ubc/knot tying"

suture_index: 3


left_image_path: "${workspace}/${suture_name}/${suture_index}/regular/image/left"
right_image_path: "${workspace}/${suture_name}/${suture_index}/regular/image/right"
side_camera_1_path: "${workspace}/${suture_name}/${suture_index}/regular/image/side"
#side_camera_1_path: None
side_camera_2_path: None

save_folder: "/home/jackzhy/tmp"

resize_max_size: False

main_image_max_size: [640, 480]
side_image_max_size: [640, 480]

enable_PSM1: True
enable_PSM2: True
enable_PSM3: False

#camera_offset:
# ### Add random seeds if required
# seed: 42

# ### Optional, define log output if required
#hydra:
#  run:
#    dir: "/home/jackzhy/dvrk_multimodal_data_collection/outputs/logs/${now:%Y%m%d}_${now:%H%M%S}"

# custom configurations
