defaults:
  - path_config: jack_local_release     # pick one file from the data, data load and store paths
  - preprocess: video_to_image  # select the preprocess type
  - _self_

workspace: "<repository root>"

video_name: 'left'

video_path: "${path_config.data_dir}/output_video/${path_config.data_name}/${path_config.data_index}/${video_name}.mp4"

output_path: "${path_config.data_dir}/output_video/frame_gen/${path_config.data_name}/${path_config.data_index}"

image_folder: "image/${video_name}"
timestamp_folder: "time_syn"

