defaults:
  - path_config: jack_local_video     # pick one file from the data, data load and store paths
  - preprocess: image_to_video  # select the preprocess type
  - _self_

workspace: "/home/jackzhy/dvrk_multimodal_data_collection"

timestamp_path: "${path_config.data_dir}/${path_config.data_name}/${path_config.data_index}/regular/time_syn"


### raw images to video
video_name: 'left'
#video_name: 'left_resized'
image_path: "${path_config.data_dir}/${path_config.data_name}/${path_config.data_index}/regular/image/left"
save_folder: "${path_config.data_dir}/output_video/data/${path_config.data_name}/${path_config.data_index}"

#video_name: 'side'
##video_name: 'side_resized'
#image_path: "${path_config.data_dir}/${path_config.data_name}/${path_config.data_index}/regular/image/side"
#save_folder: "${path_config.data_dir}/output_video/data/${path_config.data_name}/${path_config.data_index}"



### rectified images to video
#video_name: 'left_rectified'
#image_path: "${path_config.data_dir}/interm/${path_config.data_name}/${path_config.data_index}/regular/image/left"
#save_folder: "${path_config.data_dir}/output_video/interm/${path_config.data_name}/${path_config.data_index}/"

### depth estimation to video
#video_name: 'disparity_estimate'
#image_path: "${path_config.data_dir}/output/${path_config.data_name}/${path_config.data_index}/depth_estimation/depth_image"
#save_folder: "${path_config.data_dir}/output_video/output/${path_config.data_name}/${path_config.data_index}/depth_estimation"

### optical flow to video
#video_name: 'left_of'
#image_path: "${path_config.data_dir}/output/${path_config.data_name}/${path_config.data_index}/optical_flow/left/image"
#save_folder: "${path_config.data_dir}/output_video/output/${path_config.data_name}/${path_config.data_index}/optical_flow"


### kinematic map to video
##video_name: 'left_kp_PSM1'
##image_path: "${path_config.data_dir}/output/${path_config.data_name}/${path_config.data_index}/kinematic_map/PSM1/left/image"
#
#video_name: 'left_kp_PSM2'
#image_path: "${path_config.data_dir}/output/${path_config.data_name}/${path_config.data_index}/kinematic_map/PSM2/left/image"
#
#save_folder: "${path_config.data_dir}/output_video/output/${path_config.data_name}/${path_config.data_index}/kinematic_map"




















