"""
Script to assemble sequential images into a video with timestamp-based or fixed frame rate timing.
Uses FFmpeg as the primary encoder (high-quality) with OpenCV as a fallback.
Configuration managed via Hydra.

Two timing modes:
  - enable_fixed_rate: True  → all frames get equal duration 1/video_fixed_rate (default 10 Hz)
  - enable_fixed_rate: False → each frame uses its actual duration from timestamps
    Supports both timestamp formats:
      1. Simple:    {"timestamp": "seconds_nanoseconds"} (generated by video-to-image extraction)
      2. ROS-style: {"image_left_stamp": {"sec": N, "nsec": N}} (from dVRK data collection)
"""

from dataclasses import dataclass
from typing import Union, List, Optional
import hydra
from hydra.core.config_store import ConfigStore
from pathlib import Path
import numpy as np
import cv2
from tqdm import tqdm
import os
import json
import subprocess
import tempfile
import shutil
import time

from dvrk_data_processing.utils.hydra_config import ImageToVideoConfig, PathConfig
from dvrk_data_processing.utils.utility import glob_sorted_frame, create_folder


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class AppCfg:
    path_config: PathConfig
    preprocess: ImageToVideoConfig
    video_name: str
    workspace: Union[str, Path]
    image_path: Union[str, Path]
    timestamp_path: Union[str, Path]
    save_folder: Union[str, Path]


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------

def _check_ffmpeg_available() -> bool:
    """Return True if the ffmpeg binary is on PATH and executable."""
    return shutil.which("ffmpeg") is not None


def load_timestamps(timestamp_path: Path) -> np.ndarray:
    """
    Load timestamps from a directory of per-frame JSON files.

    Supports two JSON layouts:
      1. Simple format (generated by video-to-image extraction):
         {"timestamp": "seconds_nanoseconds"}
      2. ROS-style format (from dVRK data collection time_syn/ folders):
         {"image_left_stamp": {"sec": <int>, "nsec": <int>}, ...}

    Args:
        timestamp_path: Path to directory containing numbered JSON files.

    Returns:
        1-D numpy array of timestamps in seconds (sorted by frame index).
    """
    if not timestamp_path.is_dir():
        raise ValueError(f"Timestamp path must be a directory: {timestamp_path}")

    # Get all JSON files sorted numerically by stem (0.json, 1.json, ...)
    json_files = glob_sorted_frame(timestamp_path)

    timestamps: List[float] = []
    for json_file in json_files:
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)

            ts = _parse_single_timestamp(data, json_file)
            if ts is not None:
                timestamps.append(ts)

        except (json.JSONDecodeError, ValueError, KeyError) as e:
            print(f"Warning: Could not parse timestamp from {json_file}: {e}")
            continue

    return np.array(timestamps)


def _parse_single_timestamp(data: dict, source_file: Path) -> Optional[float]:
    """
    Extract a single timestamp (seconds) from one JSON dict.

    Tries formats in order:
      1. ROS-style: image_left_stamp.sec / .nsec
      2. Simple:    timestamp field as "sec_nsec" string
    """
    # --- Format 1: ROS-style with image_left_stamp ---
    if "image_left_stamp" in data:
        stamp = data["image_left_stamp"]
        sec = int(stamp["sec"])
        nsec = int(stamp["nsec"])
        return sec + nsec / 1e9

    # --- Format 2: Simple "seconds_nanoseconds" string ---
    if "timestamp" in data:
        timestamp_str = str(data["timestamp"])
        if '_' in timestamp_str:
            seconds_str, nanoseconds_str = timestamp_str.split('_')
            return float(seconds_str) + float(nanoseconds_str) / 1e9
        else:
            # Fallback: treat as a plain float
            return float(timestamp_str)

    print(f"Warning: Unrecognised timestamp format in {source_file}")
    return None


def calculate_frame_delays(timestamps: np.ndarray, fallback_fps: float) -> np.ndarray:
    """
    Compute per-frame durations (seconds) from an array of absolute timestamps.

    The first frame gets the same duration as the second (no prior reference).
    Any non-positive durations are clamped to 1 µs.

    Args:
        timestamps:   Absolute timestamps in seconds (length N).
        fallback_fps: Used only when there is a single frame.

    Returns:
        1-D array of durations (length N).
    """
    if len(timestamps) < 2:
        return np.array([1.0 / fallback_fps])

    # Consecutive differences give the duration each frame was displayed
    delays = np.diff(timestamps)
    delays = np.maximum(delays, 1e-6)  # clamp to at least 1 µs

    # First frame gets the same duration as the second frame
    return np.concatenate([[delays[0]], delays])


# ---------------------------------------------------------------------------
# FFmpeg-based encoding (primary)
# ---------------------------------------------------------------------------

def _parse_ffmpeg_progress(line: str) -> Optional[int]:
    """
    Extract the current frame number from an FFmpeg stderr progress line.

    FFmpeg periodically prints lines like:
      frame=  100 fps= 25 q=28.0 size=  256kB time=00:00:04.00 ...
    Returns the frame number if found, else None.
    """
    import re
    m = re.search(r'frame=\s*(\d+)', line)
    return int(m.group(1)) if m else None


def _create_video_ffmpeg(
    image_files: List[Path],
    output_file: Path,
    width: int,
    height: int,
    config: "AppCfg",
    frame_durations: Optional[np.ndarray] = None,
) -> bool:
    """
    Encode images into a video using FFmpeg's concat demuxer.

    For fixed-rate mode, every frame gets duration 1/fps.
    For timestamp mode, each frame gets its actual duration from *frame_durations*.
    Shows a real-time progress bar by streaming FFmpeg's stderr.

    Args:
        image_files:     Sorted list of image paths.
        output_file:     Destination .mp4 path.
        width, height:   Target resolution (used for resize filter if needed).
        config:          Full application config.
        frame_durations: Per-frame durations in seconds (None → fixed rate).

    Returns:
        True on success, False on failure.
    """
    ffmpeg_cfg = config.preprocess.ffmpeg_config
    fps = config.preprocess.video_fixed_rate
    need_resize = config.preprocess.resize_config.enable_resize
    total_frames = len(image_files)

    # --- Build the concat demuxer text file ---
    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".txt", prefix="ffmpeg_concat_")
    temp_list_file = Path(tmp_path)

    try:
        with os.fdopen(tmp_fd, 'w') as f:
            for idx, img_file in enumerate(image_files):
                f.write(f"file '{img_file.absolute()}'\n")
                if frame_durations is not None:
                    # Timestamp mode: per-frame duration
                    f.write(f"duration {frame_durations[idx]:.9f}\n")
                else:
                    # Fixed rate mode: uniform duration
                    f.write(f"duration {1.0 / fps:.9f}\n")
            # FFmpeg concat demuxer requires the last file repeated without duration
            if image_files:
                f.write(f"file '{image_files[-1].absolute()}'\n")

        # --- Assemble the ffmpeg command ---
        cmd = [
            "ffmpeg",
            "-y",                           # overwrite output
            "-f", "concat",
            "-safe", "0",
            "-i", str(temp_list_file),
        ]

        # Optional resize via scale filter
        if need_resize:
            cmd += ["-vf", f"scale={width}:{height}"]

        cmd += [
            "-c:v", ffmpeg_cfg.codec,
            "-crf", str(ffmpeg_cfg.crf),
            "-preset", ffmpeg_cfg.preset,
            "-pix_fmt", ffmpeg_cfg.pixel_format,
            "-r", str(fps),                 # output frame rate
            str(output_file),
        ]

        # --- Run FFmpeg with real-time progress tracking ---
        # Stream stderr so we can parse "frame=..." lines for the progress bar
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        pbar = tqdm(total=total_frames, desc="[FFmpeg] Encoding", unit="frame")
        stderr_lines: List[str] = []  # accumulate for error reporting

        # FFmpeg writes progress to stderr; read character-by-character
        # because lines are terminated by \r (carriage return) not \n
        buf = ""
        while True:
            ch = proc.stderr.read(1)
            if not ch:
                break
            ch = ch.decode("utf-8", errors="replace")

            if ch in ('\r', '\n'):
                stderr_lines.append(buf)
                frame_num = _parse_ffmpeg_progress(buf)
                if frame_num is not None:
                    # Update bar to the absolute frame position
                    pbar.n = min(frame_num, total_frames)
                    pbar.refresh()
                buf = ""
            else:
                buf += ch

        proc.wait()
        pbar.n = total_frames
        pbar.refresh()
        pbar.close()

        if proc.returncode != 0:
            print(f"Warning: FFmpeg encoding failed (rc={proc.returncode}):")
            # Print last few stderr lines for diagnosis
            for line in stderr_lines[-10:]:
                if line.strip():
                    print(f"  {line.strip()}")
            return False

        return True

    except FileNotFoundError:
        print("Warning: FFmpeg binary not found")
        return False

    finally:
        # Always clean up the temporary concat list
        if temp_list_file.exists():
            temp_list_file.unlink()


# ---------------------------------------------------------------------------
# OpenCV-based encoding (fallback)
# ---------------------------------------------------------------------------

def _create_video_opencv(
    image_files: List[Path],
    output_file: Path,
    width: int,
    height: int,
    config: "AppCfg",
    frame_durations: Optional[np.ndarray] = None,
) -> bool:
    """
    Fallback encoder using cv2.VideoWriter.

    For timestamp mode the only option is to repeat frames proportionally
    to approximate the real timing (VideoWriter has a fixed fps).

    Args:
        image_files:     Sorted list of image paths.
        output_file:     Destination .mp4 path.
        width, height:   Target resolution.
        config:          Full application config.
        frame_durations: Per-frame durations in seconds (None → fixed rate).

    Returns:
        True on success, False on failure.
    """
    fps = config.preprocess.video_fixed_rate
    need_resize = config.preprocess.resize_config.enable_resize

    # Use mp4v codec for the OpenCV fallback (widely supported)
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(output_file), fourcc, fps, (width, height))

    if not writer.isOpened():
        print(f"Warning: OpenCV VideoWriter failed to open {output_file}")
        return False

    for idx, image_file in enumerate(tqdm(image_files, desc="[OpenCV] Encoding", unit="frame")):
        image = cv2.imread(str(image_file))
        if image is None:
            print(f"Warning: Could not read image {image_file}, skipping...")
            continue

        if need_resize:
            image = cv2.resize(image, (width, height))

        if frame_durations is not None:
            # Approximate variable timing by repeating frames
            repeat_count = max(1, int(frame_durations[idx] * fps))
            for _ in range(repeat_count):
                writer.write(image)
        else:
            writer.write(image)

    writer.release()
    return True


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def create_video_from_images(config: AppCfg) -> None:
    """
    Create a video from sequential images.

    Tries FFmpeg first for high-quality encoding.  Falls back to OpenCV if
    FFmpeg is not installed or the encoding fails.

    Args:
        config: Hydra application config.
    """
    image_path = Path(config.image_path)
    output_path = Path(config.save_folder)

    # --- Validate input ---
    if not image_path.exists():
        raise FileNotFoundError(f"Image directory not found: {image_path}")
    if not image_path.is_dir():
        raise ValueError(f"Image path is not a directory: {image_path}")

    # Ensure output directory exists
    if not output_path.exists():
        create_folder(output_path)

    # --- Gather and slice image files ---
    image_files = glob_sorted_frame(image_path)
    print(f"Found {len(image_files)} total images")

    start_idx = 0 if config.preprocess.start_frame == -1 else config.preprocess.start_frame
    end_idx = len(image_files) if config.preprocess.end_frame == -1 else config.preprocess.end_frame + 1

    # Clamp to valid range
    start_idx = max(0, min(start_idx, len(image_files) - 1))
    end_idx = max(start_idx + 1, min(end_idx, len(image_files)))
    image_files = image_files[start_idx:end_idx]
    print(f"Processing frames {start_idx} to {end_idx - 1} ({len(image_files)} images)")

    if not image_files:
        raise ValueError("No image files found after applying frame range")

    # --- Determine output dimensions ---
    first_image = cv2.imread(str(image_files[0]))
    if first_image is None:
        raise ValueError(f"Could not read first image: {image_files[0]}")
    original_height, original_width = first_image.shape[:2]

    if config.preprocess.resize_config.enable_resize:
        width, height = config.preprocess.resize_config.new_size
    else:
        width, height = original_width, original_height

    # --- Load timestamps if using variable-rate timing ---
    frame_durations = None  # None signals fixed-rate to the encoders
    if not config.preprocess.enable_fixed_rate:
        if config.timestamp_path is None:
            raise ValueError("timestamp_path is required when enable_fixed_rate is False")

        timestamp_path = Path(config.timestamp_path)
        if not timestamp_path.exists():
            raise FileNotFoundError(f"Timestamp path not found: {timestamp_path}")

        timestamps = load_timestamps(timestamp_path)
        print(f"Loaded {len(timestamps)} total timestamps")

        # Apply the same frame range to timestamps
        ts_start = max(0, min(start_idx, len(timestamps) - 1))
        ts_end = max(ts_start + 1, min(end_idx, len(timestamps)))
        timestamps = timestamps[ts_start:ts_end]
        print(f"Using timestamps {ts_start} to {ts_end - 1} ({len(timestamps)} timestamps)")

        if len(timestamps) != len(image_files):
            raise ValueError(
                f"Number of timestamps ({len(timestamps)}) doesn't match "
                f"number of images ({len(image_files)})"
            )

        frame_durations = calculate_frame_delays(timestamps, config.preprocess.video_fixed_rate)

        total_dur = timestamps[-1] - timestamps[0] if len(timestamps) > 1 else 1.0
        avg_fps = len(image_files) / total_dur if total_dur > 0 else config.preprocess.video_fixed_rate
        print(f"Timestamp-based timing  |  total duration: {total_dur:.2f}s  |  avg fps: {avg_fps:.2f}")
    else:
        print(f"Fixed frame rate: {config.preprocess.video_fixed_rate} fps")

    # --- Encode ---
    output_file = output_path / f"{config.video_name}.mp4"

    use_ffmpeg = _check_ffmpeg_available()
    success = False
    t_start = time.time()

    if use_ffmpeg:
        print(f"Encoding with FFmpeg ({config.preprocess.ffmpeg_config.codec}, "
              f"crf={config.preprocess.ffmpeg_config.crf}, "
              f"preset={config.preprocess.ffmpeg_config.preset})")
        success = _create_video_ffmpeg(
            image_files, output_file, width, height, config, frame_durations,
        )
        if not success:
            print("FFmpeg encoding failed — falling back to OpenCV")
    else:
        print("FFmpeg not found on PATH — using OpenCV fallback")

    if not success:
        print("Encoding with OpenCV (mp4v codec)")
        success = _create_video_opencv(
            image_files, output_file, width, height, config, frame_durations,
        )

    elapsed = time.time() - t_start
    if success:
        # Show file size alongside the path
        size_mb = output_file.stat().st_size / (1024 * 1024)
        print(f"Video saved to: {output_file}  ({size_mb:.1f} MB)")
        print(f"Encoding completed in {elapsed:.1f}s  "
              f"({len(image_files)} frames, {len(image_files)/elapsed:.1f} frames/s)")
    else:
        print(f"Error: Failed to create video at {output_file}  (elapsed {elapsed:.1f}s)")


# ---------------------------------------------------------------------------
# Hydra entry point
# ---------------------------------------------------------------------------

cs = ConfigStore.instance()
cs.store(name="image_to_video", node=AppCfg)

# Set config path
p_config = Path.cwd().parents[0] / 'config'


@hydra.main(
    version_base=None,
    config_path=str(p_config),
    config_name="config_i2v_jack"
)
def main(cfg: AppCfg) -> None:
    """
    Main function to convert images to video using hydra configuration.

    Args:
        cfg: ImageToVideoConfig object
    """
    # Create video
    create_video_from_images(cfg)


if __name__ == '__main__':
    main()
    print('Image to video conversion completed!')
